// @generated by tools/gen_board.py -- DO NOT EDIT.
// Regenerate with `make board` (or `uv run python tools/gen_board.py`).
//!
//! Generated board constants, the Rust half of the pair emitted by
//! `tools/gen_board.py`. The Python half is `ticket_to_ride/data/board_gen.py`;
//! the two are emitted from one canonicalized spec so the engines cannot disagree
//! about the board itself. Indices and DATA_HASH are frozen -- see docs/CONTRACT.md.

#![allow(dead_code)]

pub const SCHEMA_VERSION: u32 = 1;

/// One board's data. Mirrors `ticket_to_ride.data.rawmap.RawMap` field for field.
pub struct RawMap {
    pub name: &'static str,
    pub cities: &'static [&'static str],
    /// (city_a, city_b, length, color); color 255 = gray.
    pub segments: &'static [(u8, u8, u8, u8)],
    /// (city_a, city_b, points)
    pub tickets: &'static [(u8, u8, u8)],
    pub color_names: &'static [&'static str],
    pub trains_per_player: u8,
    pub cards_per_color: u8,
    pub locomotives: u8,
    /// Indexed by route length; index 0 is unused.
    pub route_points: &'static [u8],
    pub longest_bonus: u8,
    pub initial_ticket_deal: u8,
    pub initial_ticket_keep_min: u8,
    pub draw_ticket_deal: u8,
    pub draw_ticket_keep_min: u8,
    pub min_players: u8,
    pub max_players: u8,
    pub data_hash: &'static str,
}

impl RawMap {
    #[inline]
    pub const fn locomotive(&self) -> u8 {
        self.color_names.len() as u8
    }

    #[inline]
    pub const fn n_card_types(&self) -> usize {
        self.color_names.len() + 1
    }
}

pub const USA_CITIES: [&str; 36] = [
    "Atlanta", "Boston", "Calgary", "Charleston", "Chicago", "Dallas", "Denver", "Duluth", "El Paso", "Helena", "Houston", "Kansas City", "Las Vegas", "Little Rock", "Los Angeles", "Miami", "Montreal", "Nashville", "New Orleans", "New York", "Oklahoma City", "Omaha", "Phoenix", "Pittsburgh", "Portland", "Raleigh", "Saint Louis", "Salt Lake City", "San Francisco", "Santa Fe", "Sault St. Marie", "Seattle", "Toronto", "Vancouver", "Washington", "Winnipeg",
];

pub const USA_SEGMENTS: [(u8, u8, u8, u8); 100] = [
    (0, 3, 2, 255), (0, 15, 5, 1), (0, 17, 1, 255), (0, 18, 4, 3),
    (0, 18, 4, 7), (0, 25, 2, 255), (0, 25, 2, 255), (1, 16, 2, 255),
    (1, 16, 2, 255), (1, 19, 2, 5), (1, 19, 2, 7), (2, 9, 4, 255),
    (2, 31, 4, 255), (2, 33, 3, 255), (2, 35, 6, 6), (3, 15, 4, 4),
    (3, 25, 2, 255), (4, 7, 3, 5), (4, 21, 4, 1), (4, 23, 3, 0),
    (4, 23, 3, 3), (4, 26, 2, 2), (4, 26, 2, 6), (4, 32, 4, 6),
    (5, 8, 4, 5), (5, 10, 1, 255), (5, 10, 1, 255), (5, 13, 2, 255),
    (5, 20, 2, 255), (5, 20, 2, 255), (6, 9, 4, 2), (6, 11, 4, 0),
    (6, 11, 4, 3), (6, 20, 4, 5), (6, 21, 4, 4), (6, 22, 5, 6),
    (6, 27, 3, 5), (6, 27, 3, 7), (6, 29, 2, 255), (7, 9, 6, 3),
    (7, 21, 2, 255), (7, 21, 2, 255), (7, 30, 3, 255), (7, 32, 6, 4),
    (7, 35, 4, 0), (8, 10, 6, 2), (8, 14, 6, 0), (8, 20, 5, 7),
    (8, 22, 3, 255), (8, 29, 2, 255), (9, 21, 5, 5), (9, 27, 3, 4),
    (9, 31, 6, 7), (9, 35, 4, 1), (10, 18, 2, 255), (11, 20, 2, 255),
    (11, 20, 2, 255), (11, 21, 1, 255), (11, 21, 1, 255), (11, 26, 2, 1),
    (11, 26, 2, 4), (12, 14, 2, 255), (12, 27, 3, 3), (13, 17, 3, 6),
    (13, 18, 3, 2), (13, 20, 2, 255), (13, 26, 2, 255), (14, 22, 3, 255),
    (14, 28, 3, 4), (14, 28, 3, 7), (15, 18, 6, 5), (16, 19, 3, 1),
    (16, 30, 5, 0), (16, 32, 3, 255), (17, 23, 4, 7), (17, 25, 3, 0),
    (17, 26, 2, 255), (19, 23, 2, 2), (19, 23, 2, 6), (19, 34, 2, 0),
    (19, 34, 2, 3), (20, 29, 3, 1), (22, 29, 3, 255), (23, 25, 2, 255),
    (23, 26, 5, 2), (23, 32, 2, 255), (23, 34, 2, 255), (24, 27, 6, 1),
    (24, 28, 5, 2), (24, 28, 5, 4), (24, 31, 1, 255), (24, 31, 1, 255),
    (25, 34, 2, 255), (25, 34, 2, 255), (27, 28, 5, 3), (27, 28, 5, 6),
    (30, 32, 2, 255), (30, 35, 6, 255), (31, 33, 1, 255), (31, 33, 1, 255),
];

pub const USA_TICKETS: [(u8, u8, u8); 30] = [
    (0, 16, 9), (0, 19, 6), (0, 28, 17), (1, 15, 12), (2, 22, 13),
    (2, 27, 7), (4, 14, 16), (4, 18, 7), (4, 29, 9), (5, 19, 11),
    (6, 8, 4), (6, 23, 11), (7, 8, 10), (7, 10, 8), (9, 14, 8),
    (10, 11, 5), (10, 35, 12), (13, 35, 11), (14, 15, 20), (14, 19, 21),
    (14, 31, 9), (15, 32, 10), (16, 18, 13), (16, 33, 20), (17, 24, 17),
    (17, 30, 8), (19, 31, 22), (20, 30, 9), (22, 24, 11), (29, 33, 13),
];

pub const USA_COLOR_NAMES: [&str; 8] = ["black", "blue", "green", "orange", "purple", "red", "white", "yellow",];

pub const USA: RawMap = RawMap {
    name: "usa",
    cities: &USA_CITIES,
    segments: &USA_SEGMENTS,
    tickets: &USA_TICKETS,
    color_names: &USA_COLOR_NAMES,
    trains_per_player: 45,
    cards_per_color: 12,
    locomotives: 14,
    route_points: &[0, 1, 2, 4, 7, 10, 15],
    longest_bonus: 10,
    initial_ticket_deal: 3,
    initial_ticket_keep_min: 2,
    draw_ticket_deal: 3,
    draw_ticket_keep_min: 1,
    min_players: 2,
    max_players: 5,
    data_hash: "1e5e154018541e483aba9c4ba702396c",
};

pub const MINI_CITIES: [&str; 14] = [
    "Calgary", "Denver", "El Paso", "Helena", "Las Vegas", "Los Angeles", "Phoenix", "Portland", "Salt Lake City", "San Francisco", "Santa Fe", "Seattle", "Vancouver", "Winnipeg",
];

pub const MINI_SEGMENTS: [(u8, u8, u8, u8); 30] = [
    (0, 3, 4, 1), (0, 11, 4, 255), (0, 12, 3, 255), (0, 13, 5, 0),
    (1, 3, 4, 0), (1, 6, 5, 3), (1, 8, 3, 4), (1, 8, 3, 5),
    (1, 10, 2, 255), (2, 5, 5, 0), (2, 6, 3, 255), (2, 10, 2, 255),
    (3, 8, 3, 4), (3, 11, 5, 5), (3, 13, 4, 1), (4, 5, 2, 255),
    (4, 8, 3, 3), (5, 6, 3, 255), (5, 9, 3, 2), (5, 9, 3, 5),
    (6, 10, 3, 255), (7, 8, 5, 1), (7, 9, 5, 2), (7, 9, 5, 4),
    (7, 11, 1, 255), (7, 11, 1, 255), (8, 9, 5, 2), (8, 9, 5, 3),
    (11, 12, 1, 255), (11, 12, 1, 255),
];

pub const MINI_TICKETS: [(u8, u8, u8); 14] = [
    (0, 1, 8), (0, 8, 7), (1, 5, 8), (1, 9, 8), (1, 12, 10),
    (2, 7, 12), (2, 11, 13), (2, 12, 14), (3, 5, 8), (4, 13, 10),
    (5, 11, 9), (6, 13, 13), (9, 13, 12), (10, 12, 12),
];

pub const MINI_COLOR_NAMES: [&str; 6] = ["black", "blue", "green", "orange", "red", "yellow",];

pub const MINI: RawMap = RawMap {
    name: "mini",
    cities: &MINI_CITIES,
    segments: &MINI_SEGMENTS,
    tickets: &MINI_TICKETS,
    color_names: &MINI_COLOR_NAMES,
    trains_per_player: 20,
    cards_per_color: 8,
    locomotives: 6,
    route_points: &[0, 1, 2, 4, 7, 10],
    longest_bonus: 10,
    initial_ticket_deal: 3,
    initial_ticket_keep_min: 2,
    draw_ticket_deal: 3,
    draw_ticket_keep_min: 1,
    min_players: 2,
    max_players: 4,
    data_hash: "103c6ccf956f42fa082881b0b3e9f9f9",
};

pub const MAPS: [&RawMap; 2] = [&USA, &MINI];
