// @generated by tools/gen_obs_spec.py -- DO NOT EDIT.
// Regenerate with `make board`.
//!
//! Observation feature-spec table, the Rust half of the pair declared in
//! `ticket_to_ride/rl/encode/spec.py`. Both encoders read these offsets, so the
//! Rust encoder and the Python oracle cannot drift apart on layout -- only on
//! the value written into a slot, which is what the differential harness checks.

#![allow(dead_code)]

// The generated tables below carry `#[rustfmt::skip]`; see tools/gen_board.py for
// the full reasoning. Short version: without it the fmt hook and `make board`
// rewrite each other forever, and the file-wide inner form does not compile.

pub const OBS_VERSION: u32 = 1;

// The thermometer bucket edges and the opponent-slot count. Emitted rather than
// re-typed in Rust: the generated tables already guarantee the two encoders agree
// on a thermometer's *width*, and without these they could still disagree about
// where its steps fall -- a divergence that shows up as a wrong feature value with
// a perfectly correct layout, which is the hardest kind to find.
pub const HAND_BUCKETS: [u8; 7] = [1, 2, 3, 4, 5, 6, 7];
pub const COST_BUCKETS: [u16; 6] = [1, 3, 5, 8, 12, 17];
pub const TRAIN_BUCKETS: [u8; 7] = [1, 3, 6, 10, 15, 25, 35];

/// Opponent slots are pinned at the maximum table size so one network plays any
/// seat count; unused slots are zeroed and carry a `present` flag.
pub const OPPONENT_SLOTS: usize = 4;

pub struct ObsField {
    pub name: &'static str,
    /// Offset within one entity of the enclosing block.
    pub offset: usize,
    pub width: usize,
}

pub struct ObsBlock {
    pub name: &'static str,
    /// Entities this block repeats over; 1 for a singleton.
    pub count: usize,
    /// Floats per entity.
    pub stride: usize,
    /// Absolute offset of entity 0.
    pub offset: usize,
    pub fields: &'static [ObsField],
}

pub struct ObsSpec {
    pub map: &'static str,
    pub size: usize,
    pub blocks: &'static [ObsBlock],
}

#[rustfmt::skip]
const USA_SEGMENT_STATIC_FIELDS: &[ObsField] = &[
    ObsField { name: "required_color", offset: 0, width: 9 },
];

#[rustfmt::skip]
const USA_SEGMENT_DYNAMIC_FIELDS: &[ObsField] = &[
    ObsField { name: "owner", offset: 0, width: 6 },
    ObsField { name: "closed", offset: 6, width: 1 },
    ObsField { name: "twin_locked", offset: 7, width: 1 },
    ObsField { name: "can_afford_now", offset: 8, width: 1 },
    ObsField { name: "cards_short", offset: 9, width: 7 },
    ObsField { name: "on_my_steiner_tree", offset: 16, width: 1 },
    ObsField { name: "extends_my_chain", offset: 17, width: 1 },
];

#[rustfmt::skip]
const USA_OWN_HAND_FIELDS: &[ObsField] = &[
    ObsField { name: "counts", offset: 0, width: 9 },
    ObsField { name: "thermometer", offset: 9, width: 9 },
    ObsField { name: "thermometer2", offset: 18, width: 9 },
    ObsField { name: "thermometer3", offset: 27, width: 9 },
    ObsField { name: "thermometer4", offset: 36, width: 9 },
    ObsField { name: "thermometer5", offset: 45, width: 9 },
    ObsField { name: "thermometer6", offset: 54, width: 9 },
];

#[rustfmt::skip]
const USA_TICKETS_FIELDS: &[ObsField] = &[
    ObsField { name: "held", offset: 0, width: 1 },
    ObsField { name: "connected", offset: 1, width: 1 },
    ObsField { name: "remaining_cost", offset: 2, width: 1 },
    ObsField { name: "cost_thermometer", offset: 3, width: 6 },
    ObsField { name: "is_dead", offset: 9, width: 1 },
    ObsField { name: "points", offset: 10, width: 1 },
    ObsField { name: "fragility", offset: 11, width: 1 },
];

#[rustfmt::skip]
const USA_STEINER_FIELDS: &[ObsField] = &[
    ObsField { name: "remaining_cost", offset: 0, width: 1 },
    ObsField { name: "cost_minus_trains", offset: 1, width: 1 },
    ObsField { name: "exact", offset: 2, width: 1 },
];

#[rustfmt::skip]
const USA_FACEUP_FIELDS: &[ObsField] = &[
    ObsField { name: "card", offset: 0, width: 10 },
];

#[rustfmt::skip]
const USA_PILES_FIELDS: &[ObsField] = &[
    ObsField { name: "deck_size", offset: 0, width: 1 },
    ObsField { name: "discard_size", offset: 1, width: 1 },
    ObsField { name: "ticket_deck_size", offset: 2, width: 1 },
    ObsField { name: "discard_composition", offset: 3, width: 9 },
    ObsField { name: "unseen", offset: 12, width: 9 },
];

#[rustfmt::skip]
const USA_OPPONENTS_FIELDS: &[ObsField] = &[
    ObsField { name: "present", offset: 0, width: 1 },
    ObsField { name: "trains", offset: 1, width: 1 },
    ObsField { name: "trains_thermometer", offset: 2, width: 7 },
    ObsField { name: "score", offset: 9, width: 1 },
    ObsField { name: "hand_size", offset: 10, width: 1 },
    ObsField { name: "ticket_count", offset: 11, width: 1 },
    ObsField { name: "blind_draws", offset: 12, width: 1 },
    ObsField { name: "segments_claimed", offset: 13, width: 1 },
    ObsField { name: "longest_chain", offset: 14, width: 1 },
    ObsField { name: "certain", offset: 15, width: 9 },
    ObsField { name: "max_possible", offset: 24, width: 9 },
];

#[rustfmt::skip]
const USA_CLOCK_FIELDS: &[ObsField] = &[
    ObsField { name: "phase", offset: 0, width: 5 },
    ObsField { name: "seats", offset: 5, width: 5 },
    ObsField { name: "draws_left", offset: 10, width: 1 },
    ObsField { name: "final_triggered", offset: 11, width: 1 },
    ObsField { name: "final_countdown", offset: 12, width: 1 },
    ObsField { name: "turn", offset: 13, width: 1 },
    ObsField { name: "my_trains", offset: 14, width: 1 },
    ObsField { name: "my_trains_thermometer", offset: 15, width: 7 },
    ObsField { name: "my_score", offset: 22, width: 1 },
    ObsField { name: "my_ticket_count", offset: 23, width: 1 },
    ObsField { name: "score_rank", offset: 24, width: 1 },
    ObsField { name: "gap_to_leader", offset: 25, width: 1 },
];

#[rustfmt::skip]
const USA_BLOCKS: &[ObsBlock] = &[
    ObsBlock { name: "segment_static", count: 100, stride: 9, offset: 0, fields: USA_SEGMENT_STATIC_FIELDS },
    ObsBlock { name: "segment_dynamic", count: 100, stride: 18, offset: 900, fields: USA_SEGMENT_DYNAMIC_FIELDS },
    ObsBlock { name: "own_hand", count: 1, stride: 63, offset: 2700, fields: USA_OWN_HAND_FIELDS },
    ObsBlock { name: "tickets", count: 30, stride: 12, offset: 2763, fields: USA_TICKETS_FIELDS },
    ObsBlock { name: "steiner", count: 1, stride: 3, offset: 3123, fields: USA_STEINER_FIELDS },
    ObsBlock { name: "faceup", count: 5, stride: 10, offset: 3126, fields: USA_FACEUP_FIELDS },
    ObsBlock { name: "piles", count: 1, stride: 21, offset: 3176, fields: USA_PILES_FIELDS },
    ObsBlock { name: "opponents", count: 4, stride: 33, offset: 3197, fields: USA_OPPONENTS_FIELDS },
    ObsBlock { name: "clock", count: 1, stride: 26, offset: 3329, fields: USA_CLOCK_FIELDS },
];

#[rustfmt::skip]
pub const USA_OBS: ObsSpec = ObsSpec {
    map: "usa",
    size: 3355,
    blocks: USA_BLOCKS,
};

#[rustfmt::skip]
const MINI_SEGMENT_STATIC_FIELDS: &[ObsField] = &[
    ObsField { name: "required_color", offset: 0, width: 7 },
];

#[rustfmt::skip]
const MINI_SEGMENT_DYNAMIC_FIELDS: &[ObsField] = &[
    ObsField { name: "owner", offset: 0, width: 6 },
    ObsField { name: "closed", offset: 6, width: 1 },
    ObsField { name: "twin_locked", offset: 7, width: 1 },
    ObsField { name: "can_afford_now", offset: 8, width: 1 },
    ObsField { name: "cards_short", offset: 9, width: 7 },
    ObsField { name: "on_my_steiner_tree", offset: 16, width: 1 },
    ObsField { name: "extends_my_chain", offset: 17, width: 1 },
];

#[rustfmt::skip]
const MINI_OWN_HAND_FIELDS: &[ObsField] = &[
    ObsField { name: "counts", offset: 0, width: 7 },
    ObsField { name: "thermometer", offset: 7, width: 7 },
    ObsField { name: "thermometer2", offset: 14, width: 7 },
    ObsField { name: "thermometer3", offset: 21, width: 7 },
    ObsField { name: "thermometer4", offset: 28, width: 7 },
    ObsField { name: "thermometer5", offset: 35, width: 7 },
    ObsField { name: "thermometer6", offset: 42, width: 7 },
];

#[rustfmt::skip]
const MINI_TICKETS_FIELDS: &[ObsField] = &[
    ObsField { name: "held", offset: 0, width: 1 },
    ObsField { name: "connected", offset: 1, width: 1 },
    ObsField { name: "remaining_cost", offset: 2, width: 1 },
    ObsField { name: "cost_thermometer", offset: 3, width: 6 },
    ObsField { name: "is_dead", offset: 9, width: 1 },
    ObsField { name: "points", offset: 10, width: 1 },
    ObsField { name: "fragility", offset: 11, width: 1 },
];

#[rustfmt::skip]
const MINI_STEINER_FIELDS: &[ObsField] = &[
    ObsField { name: "remaining_cost", offset: 0, width: 1 },
    ObsField { name: "cost_minus_trains", offset: 1, width: 1 },
    ObsField { name: "exact", offset: 2, width: 1 },
];

#[rustfmt::skip]
const MINI_FACEUP_FIELDS: &[ObsField] = &[
    ObsField { name: "card", offset: 0, width: 8 },
];

#[rustfmt::skip]
const MINI_PILES_FIELDS: &[ObsField] = &[
    ObsField { name: "deck_size", offset: 0, width: 1 },
    ObsField { name: "discard_size", offset: 1, width: 1 },
    ObsField { name: "ticket_deck_size", offset: 2, width: 1 },
    ObsField { name: "discard_composition", offset: 3, width: 7 },
    ObsField { name: "unseen", offset: 10, width: 7 },
];

#[rustfmt::skip]
const MINI_OPPONENTS_FIELDS: &[ObsField] = &[
    ObsField { name: "present", offset: 0, width: 1 },
    ObsField { name: "trains", offset: 1, width: 1 },
    ObsField { name: "trains_thermometer", offset: 2, width: 7 },
    ObsField { name: "score", offset: 9, width: 1 },
    ObsField { name: "hand_size", offset: 10, width: 1 },
    ObsField { name: "ticket_count", offset: 11, width: 1 },
    ObsField { name: "blind_draws", offset: 12, width: 1 },
    ObsField { name: "segments_claimed", offset: 13, width: 1 },
    ObsField { name: "longest_chain", offset: 14, width: 1 },
    ObsField { name: "certain", offset: 15, width: 7 },
    ObsField { name: "max_possible", offset: 22, width: 7 },
];

#[rustfmt::skip]
const MINI_CLOCK_FIELDS: &[ObsField] = &[
    ObsField { name: "phase", offset: 0, width: 5 },
    ObsField { name: "seats", offset: 5, width: 5 },
    ObsField { name: "draws_left", offset: 10, width: 1 },
    ObsField { name: "final_triggered", offset: 11, width: 1 },
    ObsField { name: "final_countdown", offset: 12, width: 1 },
    ObsField { name: "turn", offset: 13, width: 1 },
    ObsField { name: "my_trains", offset: 14, width: 1 },
    ObsField { name: "my_trains_thermometer", offset: 15, width: 7 },
    ObsField { name: "my_score", offset: 22, width: 1 },
    ObsField { name: "my_ticket_count", offset: 23, width: 1 },
    ObsField { name: "score_rank", offset: 24, width: 1 },
    ObsField { name: "gap_to_leader", offset: 25, width: 1 },
];

#[rustfmt::skip]
const MINI_BLOCKS: &[ObsBlock] = &[
    ObsBlock { name: "segment_static", count: 30, stride: 7, offset: 0, fields: MINI_SEGMENT_STATIC_FIELDS },
    ObsBlock { name: "segment_dynamic", count: 30, stride: 18, offset: 210, fields: MINI_SEGMENT_DYNAMIC_FIELDS },
    ObsBlock { name: "own_hand", count: 1, stride: 49, offset: 750, fields: MINI_OWN_HAND_FIELDS },
    ObsBlock { name: "tickets", count: 14, stride: 12, offset: 799, fields: MINI_TICKETS_FIELDS },
    ObsBlock { name: "steiner", count: 1, stride: 3, offset: 967, fields: MINI_STEINER_FIELDS },
    ObsBlock { name: "faceup", count: 5, stride: 8, offset: 970, fields: MINI_FACEUP_FIELDS },
    ObsBlock { name: "piles", count: 1, stride: 17, offset: 1010, fields: MINI_PILES_FIELDS },
    ObsBlock { name: "opponents", count: 4, stride: 29, offset: 1027, fields: MINI_OPPONENTS_FIELDS },
    ObsBlock { name: "clock", count: 1, stride: 26, offset: 1143, fields: MINI_CLOCK_FIELDS },
];

#[rustfmt::skip]
pub const MINI_OBS: ObsSpec = ObsSpec {
    map: "mini",
    size: 1169,
    blocks: MINI_BLOCKS,
};

pub const OBS_SPECS: [&ObsSpec; 2] = [&USA_OBS, &MINI_OBS];
