"""Type stubs for the Rust core.

A compiled extension carries no type information, so without this every consumer --
`ttr bench`, the differential harness, and everything Phases 5-8 build on top -- is
untyped from `ty`'s point of view, and a typo in a method name is a runtime failure
instead of a build failure.

Kept next to `Cargo.toml` and shipped by maturin. It is hand-written, so it can drift from
`src/lib.rs`; `tests/unit/rust/test_stub_matches_module.py` asserts the two agree.
"""

from collections.abc import Buffer

CONTRACT_VERSION: int

class IllegalAction(Exception):  # noqa: N818 - mirrors engine.state.IllegalAction
    """An action that is not legal in the current state."""

def contract_version() -> int: ...
def obs_version() -> int: ...
def performance_threads() -> int: ...
def random_playouts(
    map_name: str,
    n_players: int,
    games: int,
    base_seed: int = 0,
    threads: int = 1,
) -> tuple[int, int, float]:
    """Play `games` random games entirely inside Rust. Returns `(games, steps, seconds)`."""

class Game:
    def __init__(
        self, map_name: str = ..., n_players: int = ..., *, track_history: bool = ...
    ) -> None: ...
    @property
    def num_distinct_actions(self) -> int: ...
    @property
    def n_players(self) -> int: ...
    @property
    def map_name(self) -> str: ...
    @property
    def data_hash(self) -> str: ...
    @property
    def rules_hash(self) -> str: ...
    def new_initial_state(self, seed: int) -> State: ...
    def action_to_string(self, action: int) -> str: ...

class State:
    def step(self, action: int) -> None: ...
    def legal_actions(self) -> list[int]: ...
    def legal_action_mask(self) -> bytes: ...
    def state_hash(self) -> int: ...
    def position_hash(self) -> int: ...
    def serialize(self, canonical: bool = False) -> bytes: ...
    def is_terminal(self) -> bool: ...
    def current_player(self) -> int: ...
    def clone(self) -> State: ...
    def clone_into(self, dst: State) -> None: ...
    def validate(self) -> None: ...
    def history(self) -> list[int]: ...
    def hand_of(self, player: int) -> list[int]: ...
    def certain_of(self, player: int) -> list[int]: ...
    def tickets_of(self, player: int) -> list[int]: ...
    def deck_counts(self) -> list[int]: ...
    def unseen_counts(self, observer: int) -> list[int]: ...
    def final_scores(self) -> list[int]: ...
    def score_breakdown(self) -> list[tuple[int, int, int, int, int, int, int, int]]: ...
    def returns(self) -> list[float]: ...
    def winners(self) -> list[int]: ...
    def longest_trails(self) -> list[int]: ...
    def observation(self, player: int) -> list[float]: ...
    @property
    def observation_size(self) -> int: ...
    @property
    def phase(self) -> int: ...
    @property
    def phase_name(self) -> str: ...
    @property
    def turn(self) -> int: ...
    @property
    def cur(self) -> int: ...
    @property
    def draws_left(self) -> int: ...
    @property
    def final_left(self) -> int: ...
    @property
    def pass_streak(self) -> int: ...
    @property
    def trains(self) -> list[int]: ...
    @property
    def score(self) -> list[int]: ...
    @property
    def faceup(self) -> list[int]: ...
    @property
    def seg_owner(self) -> list[int]: ...
    @property
    def deck_pos(self) -> int: ...
    @property
    def tickets_remaining(self) -> int: ...
    @property
    def seed(self) -> int: ...

class VecEnv:
    def __init__(
        self,
        map_name: str = ...,
        n_players: int = ...,
        n_envs: int = ...,
        base_seed: int = ...,
        *,
        track_history: bool = ...,
    ) -> None: ...
    @property
    def n_envs(self) -> int: ...
    @property
    def obs_size(self) -> int: ...
    @property
    def n_actions(self) -> int: ...
    @property
    def seeds(self) -> list[int]: ...
    def step(self, actions: list[int]) -> None: ...
    def auto_reset(self) -> int: ...
    def observe_current(self, out: Buffer) -> None:
        """Fill `out` (`n_envs * obs_size` float32s) in place. Nothing is copied."""

    def observe_seat(self, player: int, out: Buffer) -> None: ...
    def legal_masks(self, out: Buffer) -> None:
        """Fill `out` (`n_envs * n_actions` bytes) in place. Nothing is copied."""

    def current_players(self) -> list[int]: ...
    def terminal_flags(self) -> list[int]: ...
    def state_hashes(self) -> list[int]: ...
