#!/usr/bin/env python3
"""Board-data generator: RULES.md -> usa.toml -> board_gen.py + board_gen.rs.

Three outputs, all checked in, all regenerated by one command:

    uv run python tools/gen_board.py           # rewrite the generated files
    uv run python tools/gen_board.py --check    # fail if they are stale (CI, pre-commit)

Why generate rather than load a data file at import: a JSON/TOML board parsed
independently by Python and Rust is exactly the setup where the two engines can disagree
about the board itself, which would poison differential testing at the root. One generator
emitting both languages makes that structurally impossible. It also removes the import-time
parse from twelve self-play workers and gives reviewable git diffs on the actual constants.

`usa.toml` is generated *from RULES.md* (the human source of truth). Other maps -- TTR-mini
-- are hand-authored TOML and are inputs only; this script never overwrites them.
"""

from __future__ import annotations

import argparse
import hashlib
import sys
import tomllib
from pathlib import Path
from typing import NamedTuple

REPO_ROOT = Path(__file__).resolve().parent.parent
RULES_MD = REPO_ROOT / "RULES.md"
MAPS_DIR = REPO_ROOT / "ticket_to_ride" / "data" / "maps"
OUT_PY = REPO_ROOT / "ticket_to_ride" / "data" / "board_gen.py"
OUT_RS = REPO_ROOT / "crates" / "ttr-core" / "src" / "board_gen.rs"

#: Bump when the *shape* of the generated data changes (a new RawMap field, a different
#: index convention). Board content changes move DATA_HASH, not this.
SCHEMA_VERSION = 1

GRAY = 255
GRAY_NAME = "gray"

#: A double route is exactly two parallel tracks. Three would break the sibling table.
TRACKS_PER_DOUBLE = 2

#: TTR is a two-or-more-player game; a one-seat map would silently break the end trigger.
MIN_SEATS = 2

#: Emission order of the maps, which is also the order they appear in `MAPS`.
MAP_ORDER = ("usa", "mini")

BANNER = (
    "@generated by tools/gen_board.py -- DO NOT EDIT.\n"
    "Regenerate with `make board` (or `uv run python tools/gen_board.py`).\n"
)


class Spec(NamedTuple):
    """A parsed, canonically ordered map, before hashing."""

    name: str
    cities: tuple[str, ...]
    segments: tuple[tuple[int, int, int, int], ...]
    tickets: tuple[tuple[int, int, int], ...]
    color_names: tuple[str, ...]
    trains_per_player: int
    cards_per_color: int
    locomotives: int
    #: 1-indexed by route length so `route_points[n]` is direct; index 0 is unused.
    route_points: tuple[int, ...]
    longest_bonus: int
    initial_ticket_deal: int
    initial_ticket_keep_min: int
    draw_ticket_deal: int
    draw_ticket_keep_min: int
    min_players: int
    max_players: int


# ---------------------------------------------------------------------------
# RULES.md parsing
# ---------------------------------------------------------------------------


def _table(lines: list[str], header: str) -> list[list[str]]:
    """Rows of the markdown table introduced by `header`, as stripped cell lists.

    Double routes are written with markdown-escaped pipes (``gray \\|\\| gray``). Splitting
    naively on "|" silently yields 78 segments / 256 spaces instead of 100 / 309 and *looks*
    like it worked, so the escapes are protected before the split and restored after.
    """
    start = lines.index(header) + 2
    rows: list[list[str]] = []
    for line in lines[start:]:
        if not line.startswith("|"):
            break
        protected = line.replace(r"\|", "\x00")
        rows.append([c.strip().replace("\x00", "|") for c in protected.strip("|").split("|")])
    return rows


def parse_rules_md(text: str) -> dict[str, object]:
    """Extract the USA map from RULES.md as the same dict shape a map TOML decodes to."""
    lines = text.splitlines()

    raw_segments: list[list[object]] = []
    for a, b, length, colors in _table(lines, "| From | To | Length | Color |"):
        raw_segments.extend([a, b, int(length), c.strip()] for c in colors.split("||"))

    raw_tickets = [[a, b, int(pts)] for a, b, pts in _table(lines, "| From | To | Points |")]

    colors = sorted({s[3] for s in raw_segments if s[3] != GRAY_NAME})  # ty: ignore
    cities = sorted({s[0] for s in raw_segments} | {s[1] for s in raw_segments})  # ty: ignore

    points = {int(n): int(p) for n, p in _table(lines, "| Route Length | Points Scored |")}
    route_points = [points[n] for n in range(1, max(points) + 1)]

    return {
        "schema": SCHEMA_VERSION,
        "name": "usa",
        "trains_per_player": 45,
        "min_players": 2,
        "max_players": 5,
        "longest_path_bonus": 10,
        "colors": colors,
        "cards_per_color": 12,
        "locomotives": 14,
        "route_points": route_points,
        "initial_ticket_deal": 3,
        "initial_ticket_keep_min": 2,
        "draw_ticket_deal": 3,
        "draw_ticket_keep_min": 1,
        "cities": cities,
        "segments": raw_segments,
        "tickets": raw_tickets,
    }


# ---------------------------------------------------------------------------
# Canonicalization
# ---------------------------------------------------------------------------


def to_spec(doc: dict[str, object]) -> Spec:
    """Turn a decoded map document into a `Spec` with frozen index order.

    City, color, segment and ticket ordering is *derived here*, never taken from file
    order, so a map re-transcribed in a different row order produces byte-identical output.
    """
    if doc["schema"] != SCHEMA_VERSION:
        raise ValueError(f"{doc['name']}: schema {doc['schema']!r} != {SCHEMA_VERSION}")

    cities: list[str] = sorted(doc["cities"])  # ty: ignore[invalid-argument-type]
    colors: list[str] = sorted(doc["colors"])  # ty: ignore[invalid-argument-type]
    city_ix = {c: i for i, c in enumerate(cities)}
    color_ix = {c: i for i, c in enumerate(colors)}

    segments: list[tuple[int, int, int, int]] = []
    for a, b, length, color in doc["segments"]:  # ty: ignore[not-iterable]
        u, v = sorted((city_ix[a], city_ix[b]))
        segments.append((u, v, int(length), GRAY if color == GRAY_NAME else color_ix[color]))
    # GRAY == 255 sorts last within a pair, which is what we want for readability.
    segments.sort()

    tickets: list[tuple[int, int, int]] = []
    for a, b, points in doc["tickets"]:  # ty: ignore[not-iterable]
        u, v = sorted((city_ix[a], city_ix[b]))
        tickets.append((u, v, int(points)))
    tickets.sort()

    return Spec(
        name=str(doc["name"]),
        cities=tuple(cities),
        segments=tuple(segments),
        tickets=tuple(tickets),
        color_names=tuple(colors),
        trains_per_player=int(doc["trains_per_player"]),  # ty: ignore[invalid-argument-type]
        cards_per_color=int(doc["cards_per_color"]),  # ty: ignore[invalid-argument-type]
        locomotives=int(doc["locomotives"]),  # ty: ignore[invalid-argument-type]
        route_points=(0, *(int(p) for p in doc["route_points"])),  # ty: ignore[not-iterable]
        longest_bonus=int(doc["longest_path_bonus"]),  # ty: ignore[invalid-argument-type]
        initial_ticket_deal=int(doc["initial_ticket_deal"]),  # ty: ignore[invalid-argument-type]
        initial_ticket_keep_min=int(doc["initial_ticket_keep_min"]),  # ty: ignore
        draw_ticket_deal=int(doc["draw_ticket_deal"]),  # ty: ignore[invalid-argument-type]
        draw_ticket_keep_min=int(doc["draw_ticket_keep_min"]),  # ty: ignore
        min_players=int(doc["min_players"]),  # ty: ignore[invalid-argument-type]
        max_players=int(doc["max_players"]),  # ty: ignore[invalid-argument-type]
    )


def canonical_bytes(spec: Spec) -> bytes:
    """The exact byte string DATA_HASH is taken over.

    Line-oriented and explicit rather than clever: this encoding is part of the frozen
    contract (docs/CONTRACT.md) and has to be reproducible in Rust from the spec text
    alone. Every field that can change the game appears exactly once.
    """
    out: list[str] = [f"map {spec.name}", "colors " + " ".join(spec.color_names)]
    out += [f"city {i} {c}" for i, c in enumerate(spec.cities)]
    out += [f"seg {i} {a} {b} {n} {c}" for i, (a, b, n, c) in enumerate(spec.segments)]
    out += [f"tick {i} {a} {b} {p}" for i, (a, b, p) in enumerate(spec.tickets)]
    out += [
        f"trains {spec.trains_per_player}",
        f"cards {spec.cards_per_color} {spec.locomotives}",
        "points " + " ".join(str(p) for p in spec.route_points),
        f"bonus {spec.longest_bonus}",
        f"ticketrule {spec.initial_ticket_deal} {spec.initial_ticket_keep_min}"
        f" {spec.draw_ticket_deal} {spec.draw_ticket_keep_min}",
        f"players {spec.min_players} {spec.max_players}",
        "",
    ]
    return "\n".join(out).encode()


def data_hash(spec: Spec) -> str:
    return hashlib.blake2b(canonical_bytes(spec), digest_size=16).hexdigest()


# ---------------------------------------------------------------------------
# Validation -- everything the whole engine is sized against
# ---------------------------------------------------------------------------


def validate(spec: Spec) -> None:
    """Assert every structural invariant. Runs on every map, on every generation."""
    n_cities, n_seg = len(spec.cities), len(spec.segments)
    where = f"{spec.name}:"

    assert list(spec.cities) == sorted(set(spec.cities)), f"{where} cities not sorted/unique"
    assert list(spec.color_names) == sorted(set(spec.color_names)), f"{where} colors"
    assert GRAY_NAME not in spec.color_names, f"{where} gray is not a card color"
    assert spec.min_players >= MIN_SEATS and spec.max_players >= spec.min_players

    pairs: dict[tuple[int, int], list[int]] = {}
    for i, (a, b, length, color) in enumerate(spec.segments):
        assert 0 <= a < b < n_cities, f"{where} segment {i} endpoints"
        assert 1 <= length < len(spec.route_points), f"{where} segment {i} length {length}"
        assert color == GRAY or 0 <= color < len(spec.color_names), f"{where} segment {i} color"
        pairs.setdefault((a, b), []).append(i)

    for (a, b), ids in pairs.items():
        assert len(ids) <= TRACKS_PER_DOUBLE, (
            f"{where} {spec.cities[a]}-{spec.cities[b]} has {len(ids)} tracks"
        )
        if len(ids) == TRACKS_PER_DOUBLE:
            # Siblings must be mutual and agree on length; only the color may differ.
            assert spec.segments[ids[0]][2] == spec.segments[ids[1]][2], f"{where} double length"

    # Connectivity, over city *pairs* rather than segments.
    adjacency: dict[int, set[int]] = {i: set() for i in range(n_cities)}
    for a, b in pairs:
        adjacency[a].add(b)
        adjacency[b].add(a)
    seen, stack = {0}, [0]
    while stack:
        for nb in adjacency[stack.pop()]:
            if nb not in seen:
                seen.add(nb)
                stack.append(nb)
    assert len(seen) == n_cities, f"{where} map is not connected"

    for i, (a, b, points) in enumerate(spec.tickets):
        assert 0 <= a < b < n_cities, f"{where} ticket {i} endpoints"
        assert points > 0, f"{where} ticket {i} points"
    assert len(set(spec.tickets)) == len(spec.tickets), f"{where} duplicate tickets"

    # A ticket nobody can ever complete is a data bug, not a hard ticket.
    for a, b, _ in spec.tickets:
        reached, frontier = {a}, [a]
        while frontier:
            for nb in adjacency[frontier.pop()]:
                if nb not in reached:
                    reached.add(nb)
                    frontier.append(nb)
        assert b in reached, f"{where} ticket {spec.cities[a]}-{spec.cities[b]} unreachable"

    # Enough cards to matter: the longest route must be payable from a full color run.
    longest = max(n for _, _, n, _ in spec.segments)
    assert spec.cards_per_color >= longest, f"{where} {longest}-routes are unclaimable"
    assert n_seg >= n_cities, f"{where} suspiciously sparse"


def check_usa_against_rules(spec: Spec, rules_md: str) -> None:
    """USA-only cross-checks against the two independent tables in RULES.md.

    The City Index table is a redundant transcription of the edge list; disagreement means
    one of them has a typo. This is the check that caught the pink/purple and Montreal
    normalization issues in Step 0.
    """
    lines = rules_md.splitlines()
    city_ix = {c: i for i, c in enumerate(spec.cities)}

    derived: dict[int, set[int]] = {i: set() for i in range(len(spec.cities))}
    for a, b, _, _ in spec.segments:
        derived[a].add(b)
        derived[b].add(a)

    for city, degree, connects in _table(lines, "| City | Degree | Connects to |"):
        listed = {city_ix[c.strip()] for c in connects.split(",")}
        assert listed == derived[city_ix[city]], f"City Index disagrees with edge list: {city}"
        assert int(degree) == len(listed), f"City Index degree wrong for {city}"

    header = {
        "Cities (nodes)": len(spec.cities),
        "City pairs (unique edges)": len({(a, b) for a, b, _, _ in spec.segments}),
        "Individual routes (segments)": len(spec.segments),
        "Total train-car spaces": sum(n for _, _, n, _ in spec.segments),
    }
    for label, actual in header.items():
        needle = f"- **{label}:** {actual}"
        assert needle in rules_md, f"RULES.md header disagrees: expected {needle!r}"


# ---------------------------------------------------------------------------
# Emission
# ---------------------------------------------------------------------------


def emit_toml(spec: Spec, source: str) -> str:
    """Emit a map TOML. Only used for usa.toml, whose source is RULES.md."""

    def name_of_color(c: int) -> str:
        return GRAY_NAME if c == GRAY else spec.color_names[c]

    lines = [
        f"# @generated by tools/gen_board.py from {source} -- DO NOT EDIT BY HAND.",
        "#",
        f"# {source} is the human-readable source of truth for this map. To change the",
        "# board, edit it and re-run `make board`.",
        f"schema = {SCHEMA_VERSION}",
        f'name = "{spec.name}"',
        f"trains_per_player = {spec.trains_per_player}",
        f"min_players = {spec.min_players}",
        f"max_players = {spec.max_players}",
        f"longest_path_bonus = {spec.longest_bonus}",
        "colors = [" + ", ".join(f'"{c}"' for c in spec.color_names) + "]",
        f"cards_per_color = {spec.cards_per_color}",
        f"locomotives = {spec.locomotives}",
        "# route_points[i] scores a route of length i+1.",
        "route_points = [" + ", ".join(str(p) for p in spec.route_points[1:]) + "]",
        f"initial_ticket_deal = {spec.initial_ticket_deal}",
        f"initial_ticket_keep_min = {spec.initial_ticket_keep_min}",
        f"draw_ticket_deal = {spec.draw_ticket_deal}",
        f"draw_ticket_keep_min = {spec.draw_ticket_keep_min}",
        "",
        "# City index order is this list's order, which the generator sorts.",
        "cities = [",
    ]
    lines += [f'  "{c}",' for c in spec.cities]
    lines += [
        "]",
        "",
        '# [from, to, length, color]; "gray" accepts a set of any one color.',
        "segments = [",
    ]
    lines += [
        f'  ["{spec.cities[a]}", "{spec.cities[b]}", {n}, "{name_of_color(c)}"],'
        for a, b, n, c in spec.segments
    ]
    lines += ["]", "", "# [from, to, points]", "tickets = ["]
    lines += [f'  ["{spec.cities[a]}", "{spec.cities[b]}", {p}],' for a, b, p in spec.tickets]
    lines += ["]", ""]
    return "\n".join(lines)


def _py_tuples(rows: tuple[tuple[int, ...], ...], per_line: int) -> list[str]:
    cells = ["(" + ", ".join(str(v) for v in row) + ")," for row in rows]
    return ["        " + " ".join(cells[i : i + per_line]) for i in range(0, len(cells), per_line)]


def emit_python(specs: list[Spec]) -> str:
    lines = [
        f"# {BANNER.splitlines()[0]}",
        f"# {BANNER.splitlines()[1]}",
        '"""Generated board constants.',
        "",
        "Indices, orderings and DATA_HASH are frozen; see docs/CONTRACT.md. Nothing in here",
        "is hand-maintained -- edit RULES.md or ticket_to_ride/data/maps/*.toml instead.",
        '"""',
        "",
        "from types import MappingProxyType",
        "",
        "from ticket_to_ride.data.rawmap import RawMap",
        "",
        f"SCHEMA_VERSION = {SCHEMA_VERSION}",
        "",
    ]
    for spec in specs:
        lines += [
            f"{spec.name.upper()} = RawMap(",
            f'    name="{spec.name}",',
            "    cities=(",
        ]
        lines += [f'        "{c}",' for c in spec.cities]
        lines += ["    ),", "    segments=("]
        lines += _py_tuples(spec.segments, 4)
        lines += ["    ),", "    tickets=("]
        lines += _py_tuples(spec.tickets, 5)
        lines += [
            "    ),",
            "    color_names=(" + "".join(f'"{c}", ' for c in spec.color_names).rstrip() + "),",
            f"    trains_per_player={spec.trains_per_player},",
            f"    cards_per_color={spec.cards_per_color},",
            f"    locomotives={spec.locomotives},",
            "    route_points=(" + ", ".join(str(p) for p in spec.route_points) + "),",
            f"    longest_bonus={spec.longest_bonus},",
            f"    initial_ticket_deal={spec.initial_ticket_deal},",
            f"    initial_ticket_keep_min={spec.initial_ticket_keep_min},",
            f"    draw_ticket_deal={spec.draw_ticket_deal},",
            f"    draw_ticket_keep_min={spec.draw_ticket_keep_min},",
            f"    min_players={spec.min_players},",
            f"    max_players={spec.max_players},",
            f'    data_hash="{data_hash(spec)}",',
            ")",
            "",
        ]
    entries = ", ".join(f'"{s.name}": {s.name.upper()}' for s in specs)
    lines += [f"MAPS = MappingProxyType({{{entries}}})", ""]
    return "\n".join(lines)


def _rs_tuples(rows: tuple[tuple[int, ...], ...], per_line: int) -> list[str]:
    cells = ["(" + ", ".join(str(v) for v in row) + ")," for row in rows]
    return ["    " + " ".join(cells[i : i + per_line]) for i in range(0, len(cells), per_line)]


def emit_rust(specs: list[Spec]) -> str:
    lines = [
        f"// {BANNER.splitlines()[0]}",
        f"// {BANNER.splitlines()[1]}",
        "//!",
        "//! Generated board constants, the Rust half of the pair emitted by",
        "//! `tools/gen_board.py`. The Python half is `ticket_to_ride/data/board_gen.py`;",
        "//! the two are emitted from one canonicalized spec so the engines cannot disagree",
        "//! about the board itself. Indices and DATA_HASH are frozen -- see docs/CONTRACT.md.",
        "",
        "#![allow(dead_code)]",
        "",
        f"pub const SCHEMA_VERSION: u32 = {SCHEMA_VERSION};",
        "",
        "/// One board's data. Mirrors `ticket_to_ride.data.rawmap.RawMap` field for field.",
        "pub struct RawMap {",
        "    pub name: &'static str,",
        "    pub cities: &'static [&'static str],",
        "    /// (city_a, city_b, length, color); color 255 = gray.",
        "    pub segments: &'static [(u8, u8, u8, u8)],",
        "    /// (city_a, city_b, points)",
        "    pub tickets: &'static [(u8, u8, u8)],",
        "    pub color_names: &'static [&'static str],",
        "    pub trains_per_player: u8,",
        "    pub cards_per_color: u8,",
        "    pub locomotives: u8,",
        "    /// Indexed by route length; index 0 is unused.",
        "    pub route_points: &'static [u8],",
        "    pub longest_bonus: u8,",
        "    pub initial_ticket_deal: u8,",
        "    pub initial_ticket_keep_min: u8,",
        "    pub draw_ticket_deal: u8,",
        "    pub draw_ticket_keep_min: u8,",
        "    pub min_players: u8,",
        "    pub max_players: u8,",
        "    pub data_hash: &'static str,",
        "}",
        "",
        "impl RawMap {",
        "    #[inline]",
        "    pub const fn locomotive(&self) -> u8 {",
        "        self.color_names.len() as u8",
        "    }",
        "",
        "    #[inline]",
        "    pub const fn n_card_types(&self) -> usize {",
        "        self.color_names.len() + 1",
        "    }",
        "}",
        "",
    ]
    for spec in specs:
        up = spec.name.upper()
        lines += [
            f"pub const {up}_CITIES: [&str; {len(spec.cities)}] = [",
            "    " + " ".join(f'"{c}",' for c in spec.cities),
            "];",
            "",
            f"pub const {up}_SEGMENTS: [(u8, u8, u8, u8); {len(spec.segments)}] = [",
        ]
        lines += _rs_tuples(spec.segments, 4)
        lines += [
            "];",
            "",
            f"pub const {up}_TICKETS: [(u8, u8, u8); {len(spec.tickets)}] = [",
        ]
        lines += _rs_tuples(spec.tickets, 5)
        lines += [
            "];",
            "",
            f"pub const {up}_COLOR_NAMES: [&str; {len(spec.color_names)}] = ["
            + " ".join(f'"{c}",' for c in spec.color_names)
            + "];",
            "",
            f"pub const {up}: RawMap = RawMap {{",
            f'    name: "{spec.name}",',
            f"    cities: &{up}_CITIES,",
            f"    segments: &{up}_SEGMENTS,",
            f"    tickets: &{up}_TICKETS,",
            f"    color_names: &{up}_COLOR_NAMES,",
            f"    trains_per_player: {spec.trains_per_player},",
            f"    cards_per_color: {spec.cards_per_color},",
            f"    locomotives: {spec.locomotives},",
            "    route_points: &[" + ", ".join(str(p) for p in spec.route_points) + "],",
            f"    longest_bonus: {spec.longest_bonus},",
            f"    initial_ticket_deal: {spec.initial_ticket_deal},",
            f"    initial_ticket_keep_min: {spec.initial_ticket_keep_min},",
            f"    draw_ticket_deal: {spec.draw_ticket_deal},",
            f"    draw_ticket_keep_min: {spec.draw_ticket_keep_min},",
            f"    min_players: {spec.min_players},",
            f"    max_players: {spec.max_players},",
            f'    data_hash: "{data_hash(spec)}",',
            "};",
            "",
        ]
    refs = ", ".join(f"&{s.name.upper()}" for s in specs)
    lines += [f"pub const MAPS: [&RawMap; {len(specs)}] = [{refs}];", ""]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Driver
# ---------------------------------------------------------------------------


def build() -> dict[Path, str]:
    """Produce every generated file's intended content, keyed by path."""
    rules_md = RULES_MD.read_text(encoding="utf-8")
    usa = to_spec(parse_rules_md(rules_md))
    validate(usa)
    check_usa_against_rules(usa, rules_md)

    usa_toml = emit_toml(usa, "RULES.md")
    # The TOML emitter has to be lossless, or usa.toml quietly stops describing the board
    # the generated constants were built from.
    assert to_spec(tomllib.loads(usa_toml)) == usa, "usa.toml does not round-trip"
    out = {MAPS_DIR / "usa.toml": usa_toml}

    specs = {"usa": usa}
    for path in sorted(MAPS_DIR.glob("*.toml")):
        if path.stem == "usa":
            continue
        spec = to_spec(tomllib.loads(path.read_text(encoding="utf-8")))
        assert spec.name == path.stem, f"{path.name}: name={spec.name!r} does not match filename"
        validate(spec)
        specs[spec.name] = spec

    assert set(specs) == set(MAP_ORDER), f"maps {sorted(specs)} != expected {sorted(MAP_ORDER)}"
    ordered = [specs[n] for n in MAP_ORDER]

    # usa.toml is itself generated, so a stale one must not silently feed the emitters.
    # Everything downstream is built from `usa` parsed straight out of RULES.md.
    out[OUT_PY] = emit_python(ordered)
    out[OUT_RS] = emit_rust(ordered)
    return out


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args(argv)

    stale: list[Path] = []
    for path, content in build().items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        if args.check:
            stale.append(path)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            print(f"wrote {path.relative_to(REPO_ROOT)}")

    if stale:
        names = "\n  ".join(str(p.relative_to(REPO_ROOT)) for p in stale)
        print(f"stale generated files:\n  {names}\n\nrun: make board", file=sys.stderr)
        return 1
    if args.check:
        print("board data is up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
