#!/usr/bin/env python3
"""Emit the observation feature-spec table into Rust.

    uv run python tools/gen_obs_spec.py --check    # fail if stale (CI, pre-commit)
    uv run python tools/gen_obs_spec.py            # rewrite

The table itself lives in `ticket_to_ride/rl/encode/spec.py`; this generates the Rust half
so both encoders read the same offsets. Adding a feature is then a table edit plus one
accessor per language, not a rewrite in two.

Kept separate from `gen_board.py` on purpose: that one is the *source* of the board data and
must run without the package importing successfully, whereas this one imports the spec.
Both are wired into `make board` and into pre-commit.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

from ticket_to_ride.data.board import BOARDS  # noqa: E402
from ticket_to_ride.rl.encode.spec import OBS_VERSION, obs_spec  # noqa: E402

OUT = REPO_ROOT / "crates" / "ttr-core" / "src" / "obs_spec_gen.rs"

#: Emitted before every generated table. See tools/gen_board.py for why.
SKIP = "#[rustfmt::skip]"


def emit() -> str:
    lines = [
        "// @generated by tools/gen_obs_spec.py -- DO NOT EDIT.",
        "// Regenerate with `make board`.",
        "//!",
        "//! Observation feature-spec table, the Rust half of the pair declared in",
        "//! `ticket_to_ride/rl/encode/spec.py`. Both encoders read these offsets, so the",
        "//! Rust encoder and the Python oracle cannot drift apart on layout -- only on",
        "//! the value written into a slot, which is what the differential harness checks.",
        "",
        "#![allow(dead_code)]",
        "",
        "// The generated tables below carry `#[rustfmt::skip]`; see tools/gen_board.py for",
        "// the full reasoning. Short version: without it the fmt hook and `make board`",
        "// rewrite each other forever, and the file-wide inner form does not compile.",
        "",
        f"pub const OBS_VERSION: u32 = {OBS_VERSION};",
        "",
        "pub struct ObsField {",
        "    pub name: &'static str,",
        "    /// Offset within one entity of the enclosing block.",
        "    pub offset: usize,",
        "    pub width: usize,",
        "}",
        "",
        "pub struct ObsBlock {",
        "    pub name: &'static str,",
        "    /// Entities this block repeats over; 1 for a singleton.",
        "    pub count: usize,",
        "    /// Floats per entity.",
        "    pub stride: usize,",
        "    /// Absolute offset of entity 0.",
        "    pub offset: usize,",
        "    pub fields: &'static [ObsField],",
        "}",
        "",
        "pub struct ObsSpec {",
        "    pub map: &'static str,",
        "    pub size: usize,",
        "    pub blocks: &'static [ObsBlock],",
        "}",
        "",
    ]

    names = []
    for name in BOARDS:
        spec = obs_spec(BOARDS[name])
        up = name.upper()
        names.append(up)
        for block in spec.blocks:
            lines.append(SKIP)
            lines.append(f"const {up}_{block.name.upper()}_FIELDS: &[ObsField] = &[")
            lines += [
                f'    ObsField {{ name: "{f.name}", offset: {f.offset}, width: {f.width} }},'
                for f in block.fields
            ]
            lines += ["];", ""]

        lines.append(SKIP)
        lines.append(f"const {up}_BLOCKS: &[ObsBlock] = &[")
        for block in spec.blocks:
            lines.append(
                f'    ObsBlock {{ name: "{block.name}", count: {block.count}, '
                f"stride: {block.stride}, offset: {block.offset}, "
                f"fields: {up}_{block.name.upper()}_FIELDS }},"
            )
        lines += ["];", ""]

        lines += [
            SKIP,
            f"pub const {up}_OBS: ObsSpec = ObsSpec {{",
            f'    map: "{name}",',
            f"    size: {spec.size},",
            f"    blocks: {up}_BLOCKS,",
            "};",
            "",
        ]

    refs = ", ".join(f"&{up}_OBS" for up in names)
    lines += [f"pub const OBS_SPECS: [&ObsSpec; {len(names)}] = [{refs}];", ""]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the file is stale")
    args = parser.parse_args(argv)

    content = emit()
    current = OUT.read_text(encoding="utf-8") if OUT.exists() else None
    if current == content:
        if args.check:
            print("observation spec is up to date")
        return 0
    if args.check:
        print(f"stale: {OUT.relative_to(REPO_ROOT)}\n\nrun: make board", file=sys.stderr)
        return 1
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
